### ISSUE TITLE
Service provider pretty name is shared

### ISSUE THREAD

**Issue by sttts** [kube-bind/kube-bind#140]
See from my talk https://youtu.be/Uv0ivz5xej4?t=1213, look at the columns. Something is wrong:

<img width="525" alt="Bildschirm­foto 2022-11-21 um 19 16 30" src="https://user-images.githubusercontent.com/730123/203130221-4c0f1689-ff99-4604-a3a8-6e210ecfe3a7.png">

**Comment by pkbhowmick** [comment]
Hi @sttts,
It happened because there are one controller for each bind provider cluster. But there is no filtering in APIServiceBinding controller. APIServiceBinding controller is initialized with its provider namespace. So, when controller reconciles an APIServiceBinding from other provider, it sets incorrect pretty name. That's why Provider name is inconsistent. Linked PR should solve the issue.
